import funcs as f
import tests as t
import matplotlib.pyplot as plt

if __name__ == '__main__':
    ## declare data structures
    int_list = f.generate_random_int_list(100)
    int_array = f.generate_random_int_array(100)

    int_list_item = f.get_random_item_of(int_list)
    int_array_item = f.get_random_item_of(int_array)

    print("3")
    print(" ---------------------------------- ")
    print("search_in(int_list, val)")
    print(" ---------------------------------- ")
    print(f"a: {f.get_avg_duration(f.search_in(int_list, -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(int_list, int_list_item), 35)}")
    print(" ---------------------------------- ")
    print("search_bin(int_list, val)")
    print(" ---------------------------------- ")
    print(f"a: {f.get_avg_duration(f.search_bin(int_list, -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(int_list, int_list_item), 35)}")
    print(" ---------------------------------- ")
    print("search_in(int_array, val)")
    print(" ---------------------------------- ")
    print(f"a: {f.get_avg_duration(f.search_in(int_array, -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(int_array, int_array_item), 35)}")
    print(" ---------------------------------- ")
    print("search_bin(int_array, val)")
    print(" ---------------------------------- ")
    print(f"a: {f.get_avg_duration(f.search_bin(int_array, -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(int_array, int_array_item), 35)}")
    print("4")
    print(" ---------------------------------- ")
    print("search_in(int_list, val)")
    print(" ---------------------------------- ")
    print("list with 1000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_list(1000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_list(1000), int_array_item), 35)}")
    print("list with 2000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_list(2000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_list(2000), int_array_item), 35)}")
    print("list with 3000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_list(3000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_list(3000), int_array_item), 35)}")
    print("list with 4000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_list(4000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_list(4000), int_array_item), 35)}")
    print(" ---------------------------------- ")
    print("search_bin(int_list, val)")
    print(" ---------------------------------- ")
    print("list with 1000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(1000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(1000), int_array_item), 35)}")
    print("list with 2000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(2000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(2000), int_array_item), 35)}")
    print("list with 3000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(3000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(3000), int_array_item), 35)}")
    print("list with 4000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(4000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_list(4000), int_array_item), 35)}")
    print(" ---------------------------------- ")
    print("search_in(int_array, val)")
    print(" ---------------------------------- ")
    print("array with 1000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_array(1000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_array(1000), int_array_item), 35)}")
    print("array with 2000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_array(2000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_array(2000), int_array_item), 35)}")
    print("array with 3000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_array(3000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_array(3000), int_array_item), 35)}")
    print("array with 4000")
    print(f"a: {f.get_avg_duration(f.search_in(f.generate_random_int_array(4000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_in(f.generate_random_int_array(4000), int_array_item), 35)}")
    print(" ---------------------------------- ")
    print("search_bin(int_array, val)")
    print(" ---------------------------------- ")
    print("array with 1000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(1000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(1000), int_array_item), 35)}")
    print("array with 2000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(2000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(2000), int_array_item), 35)}")
    print("array with 3000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(3000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(3000), int_array_item), 35)}")
    print("array with 4000")
    print(f"a: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(4000), -1), 35)}")
    print(f"b: {f.get_avg_duration(f.search_bin(f.generate_random_int_array(4000), int_array_item), 35)}")
